<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <BuiltInComInteropSupport>true</BuiltInComInteropSupport>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
	 <UseWPF>false</UseWPF>
	 <UseAvalonia>true</UseAvalonia>
	 <!-- 需要设置这个 -->
  </PropertyGroup>
  <PropertyGroup Label="Avalonia">
    <EnableAvaloniaXamlCompilation>True</EnableAvaloniaXamlCompilation>
  </PropertyGroup>
	<ItemGroup>
		<None Update="appsettings.json">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</None>
		<!--让appsettings.json正常-->
	</ItemGroup>
	
  <ItemGroup>
    <AvaloniaResource Include="Assets\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" Version="11.3.2" />
    <PackageReference Include="Avalonia.Desktop" Version="11.3.2" />
    <PackageReference Include="Avalonia.Themes.Fluent" Version="11.3.2" />
    <PackageReference Include="Avalonia.Fonts.Inter" Version="11.3.2" />
    <!--Condition below is needed to remove Avalonia.Diagnostics package from build output in Release configuration.-->
    <PackageReference Include="Avalonia.Diagnostics" Version="11.3.2">
      <IncludeAssets Condition="'$(Configuration)' != 'Debug'">None</IncludeAssets>
      <PrivateAssets Condition="'$(Configuration)' != 'Debug'">All</PrivateAssets>
    </PackageReference>
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.2.1" />
    <PackageReference Include="LiveChartsCore.SkiaSharpView.Avalonia" Version="2.0.0-rc5.4" />
    <PackageReference Include="mameolan.Avalonia.ExtendedToolkit" Version="1.0.0-CI-20220410-063959" />
    <PackageReference Include="MessageBox.Avalonia" Version="3.2.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.6" />
    <PackageReference Include="Microsoft.Extensions.Configuration" Version="10.0.0-preview.5.25277.114" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Binder" Version="10.0.0-preview.5.25277.114" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="10.0.0-preview.5.25277.114" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.0-preview.5.25277.114" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="10.0.0-preview.5.25277.114" />
	  <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
	  <PackageReference Include="MQTTnet" Version="4.3.6.1152" />
	  <PackageReference Include="MQTTnet.Extensions.ManagedClient" Version="4.3.6.1152" />
  </ItemGroup>

  <ItemGroup>
    <AvaloniaResource Update="Assets\avalonia-logo.ico">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </AvaloniaResource>
    <AvaloniaResource Update="Assets\dhhi_logo.ico">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </AvaloniaResource>
    <AvaloniaResource Update="Assets\dhhi_logo_64x64.ico">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </AvaloniaResource>
  </ItemGroup>

</Project>
